@base_url = http://localhost:3000/c19ctavms/v1/

### Cases Data
GET {{base_url}}covid-cases-status

### Vaccination Record Status
GET {{base_url}}vaccination-records-status

### Vaccination Appointments Status
GET {{base_url}}vaccination-appointments-status