GET http://localhost:3000/citizen/visiting-logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiI4MDk1MTE1Yi0yNTViLTRjYzItODJmNC05ZjZlNDIwZjY3ZGYiLCJ1c2VyX0lEIjoiMjExYzlmN2YtMjg2Zi00MjAxLWI3YWMtMmNlNWUxM2RiZGE3IiwidXNlcl90eXBlIjoiQ2l0aXplbiIsImFjY291bnRfZGV0YWlscyI6Im1hcmlhbWVyY2VkZXpAZ21haWwuY29tIiwiaWF0IjoxNjIyMTYzMzUxLCJleHAiOjE2MjIxNjgxNTF9.ZXTgn5Z63VVn3pr-_sBUpWqCrc1ClZ7NrqFl1er8S9E
Content-Type: application/json