### All Visiting Logs

GET http://localhost:3000/citizen/visiting-logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIwZmMwZDllYi1hZDEyLTQyOTktYTNiYS1hNzhlMjRjNGM2YmUiLCJ1c2VyX0lEIjoiMjIwZmY5ZDUtNGRlMy00ZDU4LWJmOTEtOTY4YmIxMjliMmZhIiwidXNlcl90eXBlIjoiQ2l0aXplbiIsImFjY291bnRfZGV0YWlscyI6Imp1YW5kZWxhY3J1ekBnbWFpbC5jb20iLCJpYXQiOjE2MjI1MjgzMzAsImV4cCI6MTYyMjUzMzEzMH0.X3z_rdQB_L0fEwvS7-5fmdnz0yiuX37lyqn2QkmHl5s
Content-Type: application/json

### One Visiting Log
GET http://localhost:3000/citizen/visiting-logs/47490e20-ea55-47df-8a8e-bd0c416965e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiI4MDk1MTE1Yi0yNTViLTRjYzItODJmNC05ZjZlNDIwZjY3ZGYiLCJ1c2VyX0lEIjoiMjExYzlmN2YtMjg2Zi00MjAxLWI3YWMtMmNlNWUxM2RiZGE3IiwidXNlcl90eXBlIjoiQ2l0aXplbiIsImFjY291bnRfZGV0YWlscyI6Im1hcmlhbWVyY2VkZXpAZ21haWwuY29tIiwiaWF0IjoxNjIyMTgyMTMwLCJleHAiOjE2MjIxODY5MzB9.F8gZYTFc89c9n_M3ScvLkHHqufdpNv-671uOwp0bCys
Content-Type: application/json

### Add Visiting Log
POST http://localhost:3000/citizen/visiting-logs/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIwZmMwZDllYi1hZDEyLTQyOTktYTNiYS1hNzhlMjRjNGM2YmUiLCJ1c2VyX0lEIjoiMjIwZmY5ZDUtNGRlMy00ZDU4LWJmOTEtOTY4YmIxMjliMmZhIiwidXNlcl90eXBlIjoiQ2l0aXplbiIsImFjY291bnRfZGV0YWlscyI6Imp1YW5kZWxhY3J1ekBnbWFpbC5jb20iLCJpYXQiOjE2MjI1NTMxNzUsImV4cCI6MTYyMjU1Nzk3NX0.8CflztXP0MZynmGQCsKwNLPvbUCfq5_QlrRNwMnjHPM
Content-Type: application/json

{
    "establishment_ID": "aedec51e-2c46-4ead-8348-9721a1c32f5c",
    "temperature": 37.2,
    "health_status_log_ID": "0df1b48c-8fc7-4329-aea8-2a0a91ebe902",
    "purpose": "Employee"
}