### Base URL
@base_url = http://localhost:3000/c19ctavms/v1/citizen/

### AuthToken
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX0lEIjoiMjExYzlmN2YtMjg2Zi00LgjH2m5c8emE66pjdExmgep47BAdKTrCJ7Gicl90eXBlIjoiQ2l0aXplbiIsImlhdCI6MTYyNDMyNjY0NSwiZXhwIjoxNjI0MzM3NDQ1fQ.cA1ihohL-b8iY1liv7H9gXHvA8MwwHmJvQHtv6ud2Gk

### All Visiting Logs
GET {{base_url}}visiting-logs
Authorization: {{authToken}}

### One Visiting Log
GET {{base_url}}visiting-logs/47490e20-ea55-47df-8a8e-bd0c416965e1
Authorization: {{authToken}}

### Add Visiting Log
POST {{base_url}}visiting-logs/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX0lEIjoiMjExYzlmN2YtMjg2Zi00MjAxLWI3YWMtMmNlNWUxM2RiZGE3IiwidXNlcl90eXBlIjoiQ2l0aXplbiIsImlhdCI6MTYyMzQ4MjQ2MywiZXhwIjoxNjIzNDg3MjYzfQ.xkWhFDUV3Obq3gwnGFZPLe8hpvLo0tbBkCJ5UO233CE
Content-Type: application/json

{
    "establishment_ID": "aedec51e-2c46-4ead-8348-9721a1c32f5c",
    "temperature": 37.2,
    "health_status_log_ID": "0df1b48c-8fc7-4329-aea8-2a0a91ebe902",
    "purpose": "Employee"
}

### User Info
GET {{base_url}}citizen/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX0lEIjoiMjIwZmY5ZDUtNGRlMy00ZDU4LgjH2m5c8emE66pjdExmgep47BAdKTrCJ790eXBlIjoiQ2l0aXnHiSgDznyvEWLRDTty2Ej8fUgrwm3Xjt1wIjoxNjI0MzM3MjkxfQ.0DcI4RHwaHgdo-LsSta_LAP10rl4JGg-pjB9W9CvoA0