### Get All Vaccinated Citizens
GET http://localhost:3000/health-official/vaccinated-citizens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiJhNGRmMmQ0Yy05NTRmLTRjZTMtYjAyZS1mN2M2ZmU2MzU4ODIiLCJ1c2VyX0lEIjoiZWJjYWQzMDItN2MxMi00MDgzLTgxOTgtNDk1M2UwYzgzNTZhIiwidXNlcl90eXBlIjoiSGVhbHRoIE9mZmljaWFsIiwiYWNjb3VudF9kZXRhaWxzIjoiam9obmRvZUBnbWFpbC5jb20iLCJpYXQiOjE2MjI3MzM2MjcsImV4cCI6MTYyMjczODQyN30.07IcJ3WL9ZuuCj5Od5OTaB2PbClZtLCQFqWt0WK2DCg