@base_url = http://localhost:3000/c19ctavms/v1/


### Main Index
GET {{base_url}}


### Login
POST {{base_url}}login
Content-Type: application/json

{
    "auth_details": "juandelacruz@gmail.com",
    "password": "$P@ssw0rd;"
}


### Register Representative
POST {{base_url}}register/representative
Content-Type: application/json

{
    "first_name": "Richard",
    "middle_name": "A.",
    "last_name": "Soto",
    "password":  "$P@ssw0rd;",
    "user_type": "Citizen",
    "user_accounts": {
        "details": "richardsoto@gmail.com",
        "type": "Email",
        "verified": true
    },
    "establishments_with_roles": {
        "name": "DEF Company",
        "type": "Company",
        "address": {
            "region": "NATIONAL CAPITAL REGION",
            "province": "Metro Manila",
            "city_municipality": "Valenzuela City",
            "barangay_district": "Karuhatan",
            "street": "Mapulang Lupa St.",
            "specific_location": "89 Aloha Road",
            "zip_code": "1748",
            "latitude": "200",
            "longitude": "400"
        },
        "Roles": {
            "role": "Manager",
            "isAdmin": true
        }
    }
}