### Main Index
GET http://localhost:3000

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "authDetails": "johndoe@gmail.com",
    "password": "$P@ssw0rd;"
}

### Register Representative
POST http://localhost:3000/register/representative
Content-Type: application/json

{
    "first_name": "Jose",
    "middle_name": "",
    "last_name": "Alonzo",
    "user_type": "Representative",
    "password":  "$P@ssw0rd;",
    "user_accounts": {
        "details": "josealonzo@gmail.com",
        "type": "Email",
        "verified": true
    },
    "establishments_with_roles": {
        "name": "Polytechnic University of the Philippines",
        "type": "Organizational",
        "address": {
            "region": "NCR",
            "province": "Metro Manila",
            "city_municipality": "Quezon City",
            "baranggay_district": "Commonwealth",
            "street": "Don Fabian",
            "specific_location": "456",
            "zip_code": "1111",
            "latitude": "200",
            "longitude": "400"
        },
        "Roles": {
            "role": "Dean",
            "isAdmin": true
        }
    }
}

###