### Main Index
GET http://localhost:3000

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "auth_details": "johndoe@gmail.com",
    "password": "$P@ssw0rd;"
}

### Register Representative
POST http://localhost:3000/register/representative
Content-Type: application/json

{
    "first_name": "Richard",
    "middle_name": "A.",
    "last_name": "Soto",
    "password":  "$P@ssw0rd;",
    "user_type": "Citizen",
    "user_accounts": {
        "details": "richardsoto@gmail.com",
        "type": "Email",
        "verified": true
    },
    "establishments_with_roles": {
        "name": "DEF Company",
        "type": "Company",
        "address": {
            "region": "NATIONAL CAPITAL REGION",
            "province": "Metro Manila",
            "city_municipality": "Valenzuela City",
            "barangay_district": "Karuhatan",
            "street": "Mapulang Lupa St.",
            "specific_location": "89 Aloha Road",
            "zip_code": "1748",
            "latitude": "200",
            "longitude": "400"
        },
        "Roles": {
            "role": "Manager",
            "isAdmin": true
        }
    }
}

### Create Citizen

{
    "first_name": "Juan",
    "last_name": "Dela Cruz",
    "sex": "Male",
    "birth_date": "2000-01-01",
    "civil_status": "Single",
    "password": "Password",
    "user_accounts": [
        { "authDetails": "juandelacruz@gmail.com" }, 
    ],
    "address": {
        "region": "",
        "province": "",
        "city": "",
        "street": "",
        "specific_location": "",
    }
}