
GET http://localhost:3000/representative
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiI5YzI0MjlhNS1lYWJlLTRlNzMtYTM0OC00NzBlNDM4NWFjNDMiLCJ1c2VyX0lEIjoiMDdjYTZmMGItOGI5ZC00ZGU5LWFkYmMtNjIxNzIzMGFkMWYzIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJqb3NlYWxvbnpvQGdtYWlsLmNvbSIsImlhdCI6MTYyMDU1NjgwOCwiZXhwIjoxNjIwNTYxNjA4fQ.5K5sU56eTqSkQauoEQFuYXtnapG9rax_dV4v9IUcI-c

###
