### Representative
GET http://localhost:3000/representative
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIxOTAyOTA0LCJleHAiOjE2MjE5MDc3MDR9.5iGcMuc4lC2683DGlEWFx3QqV78vqGn-APEMuEym-wg

### All Establishments
GET http://localhost:3000/representative/establishment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIxOTAyOTA0LCJleHAiOjE2MjE5MDc3MDR9.5iGcMuc4lC2683DGlEWFx3QqV78vqGn-APEMuEym-wg

### Find Specific Establishment
GET http://localhost:3000/representative/establishment/4520da14-d9ad-49ea-83fc-e332f51cc6f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiJmMzdkYTk4Mi00YmQ5LTRjODUtYTIyZS1mZjczNjY0NjhiNTEiLCJ1c2VyX0lEIjoiODQzYjQ3YzEtZDgyZS00YTg1LWEwYWEtNDQzYzA4NTRhZmNjIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJtYXJpYW1lcmNlZGV6QGdtYWlsLmNvbSIsImlhdCI6MTYyMTI1NTcyMSwiZXhwIjoxNjIxMjYwNTIxfQ.RS9QzYP11HeGsQQvWh3GI3f9ntsoxCViaE7Xp4BnV6I

### Update Establishment
PUT http://localhost:3000/representative/update-establishment/45061c48-49d7-4a47-a678-d29b558afe9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiI3MGE4ZGFlMi03MzUyLTQ1MzUtYjBmZC0xMTU2MDAzNjdlYWMiLCJ1c2VyX0lEIjoiYTQ0Mzg4MzktODdmYi00MWUzLThhM2MtMzljMmNhOTVkMGJkIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJtYXJpYW1lcmNlZGV6QGdtYWlsLmNvbSIsImlhdCI6MTYyMTI1NzIxNSwiZXhwIjoxNjIxMjYyMDE1fQ.FhUWcoK6Xza_QHO8ZDQx-RMEXYXpeJeYFSSX6qiK1Yk
Content-Type: application/json

{
    "name" : "Renamed Establishment",
    "address": {
        "specific_location": "New Specific Location"
    }
}