### Representative
GET http://localhost:3000/representative
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyMTkzODkzLCJleHAiOjE2MjIxOTg2OTN9.f7xaapSgyvqA8ASRYFgNa5RIs_eX4al9iTnTn__o0rY

### Get All Establishments
GET http://localhost:3000/representative/establishments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNTcxMzIwLCJleHAiOjE2MjI1NzYxMjB9.mNYQyw1bZclDtChTpsi0KEuNFAYWF5_QkvUxdH7pqDg

### Find Specific Establishment
GET http://localhost:3000/representative/establishments/73cedc92-5152-4535-9f24-4f3160e2e358
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNjA3MTA0LCJleHAiOjE2MjI2MTE5MDR9.JNd_7wPwh-eUXElEJnx8N40ke1h79zZYpiWEBHXEEMM

### Update Establishment
PUT http://localhost:3000/representative/update-establishment/73cedc92-5152-4535-9f24-4f3160e2e358
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNjA3MTA0LCJleHAiOjE2MjI2MTE5MDR9.JNd_7wPwh-eUXElEJnx8N40ke1h79zZYpiWEBHXEEMM
Content-Type: application/json

{
    "name" : "ABC Company",
    "address": {
        "specific_location": "New Specific Location"
    }
}

### Update Representative Password
PUT http://localhost:3000/representative/update-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNzM0MzY1LCJleHAiOjE2MjI3MzkxNjV9.Oi90v1jBUAn_qK8VYPKo3dndwD0MpRyq1Fo1t8zz66E
Content-Type: application/json

{
    "password": "MyPassword"
}

### Representative Info
GET http://localhost:3000/representative/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNj

### Create Visiting Log
POST http://localhost:3000/representative/add-visiting-log
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNzM0MzY1LCJleHAiOjE2MjI3MzkxNjV9.Oi90v1jBUAn_qK8VYPKo3dndwD0MpRyq1Fo1t8zz66E
Content-Type: application/json

{
    "citizen_ID": "211c9f7f-286f-4201-b7ac-2ce5e13dbda7",
    "establishment_ID": "73cedc92-5152-4535-9f24-4f3160e2e358",
    "temperature": 35.2,
    "health_status_log_ID": "0df1b48c-8fc7-4329-aea8-2a0a91ebe902",
    "purpose": "Employee"
}

### Get All Visiting Logs
GET http://localhost:3000/representative/visiting-logs/73cedc92-5152-4535-9f24-4f3160e2e358
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiIzMjJmYTAxMS01MDE3LTRlZGYtODViYy1mOWJiMWU0M2U5MTAiLCJ1c2VyX0lEIjoiYzA3NjJjNjktNzhlOS00NjU2LThiNzktMWE2YmViZDAzNThhIiwidXNlcl90eXBlIjoiUmVwcmVzZW50YXRpdmUiLCJhY2NvdW50X2RldGFpbHMiOiJ0aW1vdGh5Lm1jZHVmZnlAZ21haWwuY29tIiwiaWF0IjoxNjIyNzM0MzY1LCJleHAiOjE2MjI3MzkxNjV9.Oi90v1jBUAn_qK8VYPKo3dndwD0MpRyq1Fo1t8zz66E