### Get All Vaccines
GET http://localhost:3000/admin/vaccines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiJiMTkyY2MzOS1jNmFkLTQ0OGMtODAzMy0xOWQ0Y2M3NjNmYzkiLCJ1c2VyX0lEIjoiMDk3MWE1MGEtZGU5Mi00NjAzLTg5YjItZmQwM2Q3NzdhODkzIiwidXNlcl90eXBlIjoiU3VwZXIgQWRtaW4iLCJhY2NvdW50X2RldGFpbHMiOiJqZXRzdW5wcmluY2V0b3JyZXNAZ21haWwuY29tIiwiaWF0IjoxNjIyNTI3MjQ3LCJleHAiOjE2MjI1MzIwNDd9.CgRXzD1cZaq5TkxzldgSoRS5OylNgYUYlMo8wXm4gAI

### Get One Vaccines
GET http://localhost:3000/admin/vaccines/77b4f71d-5546-4511-a568-900114ab9797
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiJiMTkyY2MzOS1jNmFkLTQ0OGMtODAzMy0xOWQ0Y2M3NjNmYzkiLCJ1c2VyX0lEIjoiMDk3MWE1MGEtZGU5Mi00NjAzLTg5YjItZmQwM2Q3NzdhODkzIiwidXNlcl90eXBlIjoiU3VwZXIgQWRtaW4iLCJhY2NvdW50X2RldGFpbHMiOiJqZXRzdW5wcmluY2V0b3JyZXNAZ21haWwuY29tIiwiaWF0IjoxNjIyNTI3MjQ3LCJleHAiOjE2MjI1MzIwNDd9.CgRXzD1cZaq5TkxzldgSoRS5OylNgYUYlMo8wXm4gAI

### Update Vaccine
PUT http://localhost:3000/admin/update-vaccine/77b4f71d-5546-4511-a568-900114ab9797
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2FjY291bnRfSUQiOiJiMTkyY2MzOS1jNmFkLTQ0OGMtODAzMy0xOWQ0Y2M3NjNmYzkiLCJ1c2VyX0lEIjoiMDk3MWE1MGEtZGU5Mi00NjAzLTg5YjItZmQwM2Q3NzdhODkzIiwidXNlcl90eXBlIjoiU3VwZXIgQWRtaW4iLCJhY2NvdW50X2RldGFpbHMiOiJqZXRzdW5wcmluY2V0b3JyZXNAZ21haWwuY29tIiwiaWF0IjoxNjIyNTI3MjQ3LCJleHAiOjE2MjI1MzIwNDd9.CgRXzD1cZaq5TkxzldgSoRS5OylNgYUYlMo8wXm4gAI
Content-Type: application/json

{
    "description": "This is J&J Vaccine"
}